# Generated by Django 3.1 on 2020-08-18 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollsmodel',
            options={'ordering': ('game',)},
        ),
        migrations.AlterField(
            model_name='pollsmodel',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedgame', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pollsmodel',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
