# Generated by Django 3.1 on 2020-08-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0004_remove_pollsmodel_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollsmodel',
            name='uname',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='relatedgame', to=settings.AUTH_USER_MODEL),
        ),
    ]
