# Generated by Django 3.1 on 2020-08-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20200818_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsmodel',
            name='game',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
