# Generated by Django 3.1 on 2020-08-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20200818_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalpolls',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.pollsmodel',),
        ),
        migrations.AlterModelOptions(
            name='pollsmodel',
            options={'ordering': ('uname',)},
        ),
    ]
